[project]
name = "my-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>1.24.4",
    "openai>=1.59.4",
    "openai-whisper>=20240930",
    "pyperclip>=1.9.0",
    "python-dotenv>=1.0.1",
    "soundfile>=0.13.0",
    "pyqt5-qt5==5.15.2 ; platform_system == 'Windows'",
    "pyqt5>=5.15.11",
    "keyboard>=0.13.5",
    "sounddevice>=0.5.1",
]
